services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - php_vendor:/var/www/html/vendor
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-92a1061906c2718e268de70c634d0b04}
      DATABASE_URL: mysql://app:!ChangeMe!@database:3306/poke_moveset?serverVersion=8.0&charset=utf8mb4
      MAILER_DSN: smtp://mailer:1025
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: poke_moveset
      MYSQL_USER: app
      MYSQL_PASSWORD: "!ChangeMe!"
      MYSQL_ROOT_PASSWORD: "!ChangeMe!"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p!ChangeMe!"]
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql:rw

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
  database_data:
  php_vendor:
